syntax = "proto3";
package ET;

/// 请求匹配
// ResponseType Match2G_StateSyncMatch
message G2Match_StateSyncMatch // IRequest
{
	int32 RpcId = 1;
	
	int64 Id = 2;
}

message Match2G_StateSyncMatch // IResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
}

// ResponseType Map2Match_StateSyncGetRoom
message Match2Map_StateSyncGetRoom // IRequest
{
	int32 RpcId = 1;
	repeated int64 PlayerIds = 2;
}

message Map2Match_StateSyncGetRoom // IResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
	
	/// 房间的ActorId
	ActorId ActorId = 4;
}

// ResponseType Room2G_StateSyncReconnect
message G2Room_StateSyncReconnect // IRequest
{
	int32 RpcId = 1;
	int64 PlayerId = 2;
}

message Room2G_StateSyncReconnect // IResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;

	int64 StartTime = 4;
	repeated UnitInfo UnitInfos = 5;
	int32 Frame = 6;
}

// ResponseType Room2RoomManager_StateSyncInit
message RoomManager2Room_StateSyncInit // IRequest
{
	int32 RpcId = 1;
	repeated int64 PlayerIds = 2;
}

message Room2RoomManager_StateSyncInit // IResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
}

/// 刷新匹配信息
// ResponseType G2Match_StateSyncRefreshMatch
message Match2G_StateSyncRefreshMatch // IMessage
{
	int32 RpcId = 1;
	/// 房间的ActorId
	ActorId ActorId = 2;
	/// 房间内玩家信息
	repeated int64 PlayerIds = 3;
}

message G2Match_StateSyncRefreshMatch // IResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
}


// ResponseType Match2G_CancelMatch
message G2Match_CancelMatch // IRequest
{
	int32 RpcId = 1;
	int64 PlayerId = 2;
}


// ResponseType Match2G_CreateRoom
message G2Match_CreateRoom // IRequest
{
	int32 RpcId = 1;
	int64 PlayerId = 2;
	string RoomName = 3;
	RoomMode Mode = 4;
	int32 MaxPlayers = 5;
	string Password = 6;
}

// ResponseType Match2G_GetRoomList
message G2Match_GetRoomList // IRequest
{
	int32 RpcId = 1;
	RoomMode Mode = 2;
}

// ResponseType Match2G_JoinRoom
message G2Match_JoinRoom // IRequest
{
	int32 RpcId = 1;
	int64 PlayerId = 2;
	int64 RoomId = 3;
	string Password = 4;
}

// ResponseType Match2G_LeaveRoom
message G2Match_LeaveRoom // IRequest
{
	int32 RpcId = 1;
	int64 PlayerId = 2;
}
